name: Deploy

on:
  workflow_run:
    workflows: ["Build Only"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensures deploy only if build is successful
    runs-on: ubuntu-latest
    needs: build  # Ensures deploy job only runs after build job
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # The URL of your deployed app
    env:
      AZURE_WEBAPP_NAME: 'mygoogootz'  # Define your Azure Web App name here
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app  # Ensure artifact name matches what was uploaded in the build job

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub Secrets

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Reference the environment variable here
          package: .  # Points to the current directory where the artifact was downloaded
