name: Deploy

on:
  workflow_run:
    workflows: ["Build Only"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production  # This will require approval before running the deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: '2.34.0'  # Adjust to the version of Azure CLI you need

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure you have your Azure credentials in GitHub Secrets

      - name: Deploy to Azure App Service
        run: |
          echo "Deploying to Azure App Service..."
          # Replace with your actual Azure deployment command, e.g.
          az webapp up --name <your-app-name> --resource-group <your-resource-group> --plan <your-app-service-plan>
